//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public int SchoolId { get; set; }
        public string Year { get; set; }
        public string Semester { get; set; }
        public string Day { get; set; }
        public string HourStart { get; set; }
        public string HourEnd { get; set; }
        public int GroupSubjectTeacherId { get; set; }
        public int RoomId { get; set; }
    
        public virtual School School { get; set; }
        public virtual GroupSubjectTeacher GroupSubjectTeacher { get; set; }
        public virtual Room Room { get; set; }
    }
}
