//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnavaliableHours
    {
        public int Id { get; set; }
        public string Year { get; set; }
        public string Semester { get; set; }
        public int TeacherId { get; set; }
        public int SchoolId { get; set; }
        public string Hours { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual School School { get; set; }
    }
}
